spring:
  application:
    name: fa-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  ai:
    google:
      api-key: ${GEMINI_API_KEY}
      chat:
        options:
          model: gemini-2.0-flash-lite
          temperature: 0.7
          max-output-tokens: 500

server:
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  refresh-token-validity-in-milliseconds: ${REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}

